#!/usr/bin/env python3
"""Emit one vendored CRD file: the cluster's schema, minus the cluster it came from.

Called by refresh-vendored-crds.sh, which decides WHICH CRDs to vendor. This script only knows how to
turn one live CRD into a committable file, so the two concerns stay separable and this one is testable on
its own.

WHAT IS STRIPPED, and why each: OLM writes `olm.managed` and a pair of `operators.coreos.com/<csv>.<ns>`
labels onto every CRD it owns, and `operatorframework.io/installed-alongside-<hash>` annotations naming
the exact namespaces of the install it belongs to. Committing those states that this file is OLM's copy
from one particular cluster, which is the opposite of what a vendored build-time artefact is. OLM
re-applies its own on install — verified: after `helm upgrade`, an existing CRD's `olm.managed=true` was
left untouched, because Helm skips CRDs that already exist. `status`, `uid`, `resourceVersion`,
`creationTimestamp`, `generation` and `managedFields` go for the ordinary reason that they are not inputs.

`controller-gen.kubebuilder.io/version` is KEPT: it records which generator produced the schema, which is
the one piece of provenance that makes a future schema diff readable.
"""

import argparse
import json
import subprocess
import sys

STRIP_LABEL_PREFIXES = ("olm.managed", "operators.coreos.com/")
STRIP_ANNOTATION_PREFIXES = ("operatorframework.io/installed-alongside-",)

HEADER = """# VENDORED CRD — a `helm install` mechanism, NOT this chart's declaration of ownership.
#
# WHY IT IS HERE. Helm builds the ENTIRE release manifest — hooks included — and resolves every kind
# against API discovery BEFORE it applies anything. This chart's policy CRs are {kind} objects, so on a
# cluster where the operator is not installed yet, a plain `helm install` fails at build time:
#
#     Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest:
#     resource mapping not found ... no matches for kind "{kind}" ... ensure CRDs are installed first
#
# No `helm.sh/hook-weight` and no `argocd.argoproj.io/sync-wave` can fix that — both are read long after
# the failure. Measured in an isolated sandbox chart, all three cases:
#
#     CR as a post-install hook, weight 99   fails: "unable to build kubernetes object for deleting hook"
#     CR as an ordinary resource             fails: "unable to build kubernetes objects from release manifest"
#     CRD in crds/                           ONE `helm install`, works
#
# Helm applies everything in crds/ before it renders templates, which is early enough. That is the only
# mechanism Helm offers, and it is why the sibling group-sync chart carries one too.
#
# WHAT OWNS IT AT RUNTIME: OLM, not Helm. Verified in the same sandbox, and again on a real bare-cluster
# install of this chart:
#   - on a cluster that already has the CRD, Helm SKIPS it — `helm upgrade` left an `olm.managed=true`
#     label untouched, so OLM keeps ownership and this file cannot overwrite the bundle's schema
#   - `helm uninstall` never deletes anything in crds/, so removing the release cannot cascade-delete a
#     {kind} CR or the RBAC its finalizer is responsible for
#   - on a BARE cluster Helm creates this copy first, then OLM installs the CSV moments later and
#     reconciles the CRD to the bundle's own version — measured: after one `helm install` both CRDs
#     carried `olm.managed=true` and NO `meta.helm.sh/release-name`, so Helm never claimed them
#
# UNDER ARGOCD, SET `skipCrds: true` ON THE APPLICATION. ArgoCD renders Helm sources with
# `helm template --include-crds`, so this file IS part of the Application unless you say otherwise —
# Argo would take management of it, could prune it, and would contend with OLM over its contents.
# Deleting this CRD cascades to every {kind} on the cluster. Under GitOps the readiness-wait Job
# (wave 2) plus `SkipDryRunOnMissingResource=true` on the policy CRs (wave 3) already cover the
# ordering, so Argo does not need this file at all.
#
# DO NOT EDIT BY HAND. Regenerate with:
#     working-sessions/scripts/refresh-vendored-crds.sh
# PROVENANCE: {name} as installed by {csv} — the version pinned in
# subscription.startingCSV — with OLM's cluster-specific labels and annotations stripped. Schema
# generated by controller-gen {cg}.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--crd", required=True, help="CRD name, e.g. namespaceconfigs.redhatcop.redhat.io")
    ap.add_argument("--csv", required=True, help="CSV the schema comes from, for the provenance line")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML required: pip install pyyaml")

    proc = subprocess.run(["oc", "get", "crd", args.crd, "-o", "json"], capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit("::error::could not read CRD %s: %s" % (args.crd, proc.stderr.strip()))
    live = json.loads(proc.stdout)
    meta = live["metadata"]

    labels = {k: v for k, v in (meta.get("labels") or {}).items()
              if not any(k.startswith(p) for p in STRIP_LABEL_PREFIXES)}
    annotations = {k: v for k, v in (meta.get("annotations") or {}).items()
                   if not any(k.startswith(p) for p in STRIP_ANNOTATION_PREFIXES)}

    clean = {
        "apiVersion": live["apiVersion"],
        "kind": live["kind"],
        "metadata": {"name": meta["name"]},
        "spec": live["spec"],
    }
    if annotations:
        clean["metadata"]["annotations"] = annotations
    if labels:
        clean["metadata"]["labels"] = labels

    header = HEADER.format(kind=live["spec"]["names"]["kind"], name=meta["name"], csv=args.csv,
                           cg=annotations.get("controller-gen.kubebuilder.io/version", "unknown"))
    body = yaml.dump(clean, default_flow_style=False, sort_keys=False, width=110)
    with open(args.out, "w") as fh:
        fh.write(header + body)


if __name__ == "__main__":
    main()
